version: '3.7'

services:
    postgress:
        container_name: postgres
        image: "postgres:13.2"
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        logging:
            options:
                max-size: 10m
                max-file: "3"
        ports:
            - "5432:5432"

    redis:
        container_name: redis
        image: redis
        ports:
            - "6379:6379"
        restart: always

    s3:
        container_name: s3
        image: minio/minio
        ports:
            - "9000:9000"
        environment:
            MINIO_ACCESS_KEY: S3_ACCESS_KEY
            MINIO_SECRET_KEY: S3_SECRET_KEY
        command: server /data
